version: '3'

services:
  db:
    image: karthik8898/db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - flask_network
    ports:
      - "5432:5432"

  redis:
    image: karthik8898/redis
    networks:
      - flask_network
    ports:
      - "6379:6379"

  flask:
    image: karthik8898/flaskapplication
    depends_on:
      - db
      - redis
    networks:
      - flask_network
    ports:
      - "5000:5000"

networks:
  flask_network:
    driver: bridge

volumes:
  pgdata: